# Site settings
title: The iOS Times
email: gio@mokacoding.com
description: >
  A weekly publication with news and trending projects in the open source iOS ecosystem. Curated and provided by mokagio from mokacoding.com
baseurl: "/mercury"

markdown: kramdown
