# Site settings
title: The iOS Times
email: gio@mokacoding.com
description: >
  A weekly publication with news and trending projects in the open source iOS ecosystem. Curated and provided by mokagio from mokacoding.com
baseurl: ""
permalink: none

github:
  repo: https://github.com/mokacoding/the-ios-times

# Build settings
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input:          GFM
  syntax_highlighter: rouge

future: true
